name: TestFile
approver_map:
- map_details: Applicaiton Name & Respective Approvers
  approver_category: '77'
  approver_ids: HRVIJAY
  approver_emails: hridyapraise.vijayamohan@chubb.com
name: TestFile
approver_map:
- map_details: Applicaiton Name & Respective Approvers
  approver_category: '78'
  approver_ids: HRVIJAY
  approver_emails: hridyapraise.vijayamohan@chubb.com
name: TestFile
approver_map:
- map_details: Applicaiton Name & Respective Approvers
  approver_category: '79'
  approver_ids: HRVIJAY
  approver_emails: hridyapraise.vijayamohan@chubb.com
