approver_map: null
-map_details: Applicaiton Name & Respective Approvers
approver_category: B360
approver_ids: HRVIJAY
approver_emails: hridyapraise.vijayamohan@chubb.com
? - map_details:Applicaiton Name & Respective Approvers
: approver_category: '1000'
  approver_ids: HRVIJAY
  approver_emails: hridyapraise.vijayamohan@chubb.com
map_details:Applicaiton Name & Respective Approvers:
- approver_category: B360
  approver_ids: HRVIJAY
  approver_emails: hridyapraise.vijayamohan@chubb.com
