snowflake:
- map_details: Applicaiton Name & Respective Approvers
  approver_category: '12'
  approver_ids: HRVIJAY
  approver_emails: hridyapraise.vijayamohan@chubb.com
-map_details: Applicaiton Name & Respective Approvers
approver_category: B360
approver_ids: HRVIJAY
approver_emails: hridyapraise.vijayamohan@chubb.com
