name: TestFile
approver_map:
- map_details: Applicaiton Name & Respective Approvers
  approver_category: '9'
  approver_ids: HRVIJAY
  approver_emails: hridyapraise.vijayamohan@chubb.com
name: TestFile
approver_map:
- map_details: Applicaiton Name & Respective Approvers
  approver_category: '365'
  approver_ids: HRVIJAY
  approver_emails: hridyapraise.vijayamohan@chubb.com
name: TestFile
approver_map:
- map_details: Applicaiton Name & Respective Approvers
  approver_category: '9'
  approver_ids: HRVIJAY
  approver_emails: hridyapraise.vijayamohan@chubb.com
name: TestFile
approver_map:
- map_details: Applicaiton Name & Respective Approvers
  approver_category: '777'
  approver_ids: HRVIJAY
  approver_emails: hridyapraise.vijayamohan@chubb.com
