approver_map:
- map_details: Applicaiton Name & Respective Approvers
  approver_category: B370
  approver_ids: HRVIJAY
  approver_emails: hridyapraise.vijayamohan@chubb.com
approver_map:
- map_details: Applicaiton Name & Respective Approvers
  approver_category: B380
  approver_ids: HRVIJAY
  approver_emails: hridyapraise.vijayamohan@chubb.com
approver_map:
- map_details: Applicaiton Name & Respective Approvers
  approver_category: B390
  approver_ids: HRVIJAY
  approver_emails: hridyapraise.vijayamohan@chubb.com
approver_map:
- map_details: Applicaiton Name & Respective Approvers
  approver_category: B360
  approver_ids: HRVIJAY
  approver_emails: hridyapraise.vijayamohan@chubb.com
