approver_map:
- map_details: Applicaiton Name & Respective Approvers
  approver_category: '123'
  approver_ids: abc
  approver_emails: xyz.vijayamohan@chubb.com
- map_details: Applicaiton Name & Respective Approvers
  approver_category: '456'
  approver_ids: abc
  approver_emails: xyz.vijayamohan@chubb.com

