approver_map:
- map_details: Applicaiton Name & Respective Approvers
  approver_category: '456'
  approver_ids: def
  approver_emails: mno.vijayamohan@chubb.com
-map_details: Applicaiton Name & Respective Approvers
approver_category: B360
approver_ids: HRVIJAY
approver_emails: hridyapraise.vijayamohan@chubb.com
